#pragma once

#include <random>

namespace vazel
{
    // A UUID should be a 128-bit number that is used to identify a resource.
    // This is a 64-bit number that is generated by the system and should be unique for each resource.
    // 128-bits implentation should come soon.
    using UUID = uint64_t;

    /**
     * @brief Generates a random UUID.
     *
     * @return UUID A random UUID.
     */
    UUID makeUUID(void);
}
