name: Build

on:
    push:
        branches:
        - dev
        - main
        - master
    pull_request:
jobs:
    build:
        runs-on: ubuntu:20.04
        steps:
        - uses: actions/checkout@v2
        - name: Build
          shell: bash
          run: |
            sudo apt update
            sudo apt install cmake make gcc g++ libgtest-dev libsfml-dev
            cd build && cmake .. && make
    unittests:
        runs-on: ubuntu-20.04
        steps:
        - uses: actions/checkout@v2
        - name: run_tests
          shell: bash
          run: |
            sudo apt update
            sudo apt install cmake make gcc g++ libgtest-dev libsfml-dev
            cd build && cmake .. && make
            ./tests/vazel_tests --gtest_color=yes
